### ISSUE TITLE
[Refactor][docker-compose] Add subnet mask to docker-compose

### ISSUE THREAD

**Issue by shubham-cmyk** [apache/incubator-devlake#4186]
## What and why to refactor
I am trying to add a subnet mask for the docker containers.

## Describe the solution you'd like
```
networks:
  devlake_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.1.0/24
```

## Related issues
No

## Additional context
No
