### ISSUE TITLE
[Question][Module Name] Using an RDS Instance w/ Docker Compose

### ISSUE THREAD

**Issue by AustinCloudGuru** [apache/incubator-devlake#4881]
## Question
I'm trying to deploy using the docker compose file from the latest release.  I've followed the instructions in the documentation (https://devlake.apache.org/docs/GettingStarted/DockerComposeSetup) and updated the .env file to point towards my RDS instance.  I've updated the DB_URL variable to the RDS values, but when I launch the containers, I get see the following with docker logs:  

```
Version:  v0.15.0@2fa3892
panic: Error 1045: Access denied for user 'merico'@'10.172.5.70' (using password: YES)
Wraps: (2) Error 1045: Access denied for user 'merico'@'10.172.5.70' (using password: YES)
Error types: (1) *hintdetail.withDetail (2) *mysql.MySQLError

goroutine 1 [running]:
github.com/apache/incubator-devlake/runner.CreateAppBasicRes()
        /app/runner/basic_res.go:49 +0x231
github.com/apache/incubator-devlake/services.InitResources()
        /app/services/init.go:54 +0x45
github.com/apache/incubator-devlake/services.Init()
        /app/services/init.go:80 +0x2b
github.com/apache/incubator-devlake/api.CreateApiService()
        /app/api/api.go:51 +0x2e
main.main()
        /app/main.go:39 +0x7e
```

Does anybody have an idea where this is coming from?

**Comment by klesh** [comment]
Hi, please make sure the username/password created in RDS and `DB_URL` in the `.env` are matched.

**Comment by AustinCloudGuru** [comment]
Thanks.  They do match.  I should have written my question better.  The 10.172.5.70 address is for the instance that I am running the docker containers on.  It seems like it is not honoring the DB_URL in the .env file.  My DB_URL entry in my .env file (password and instance obfuscated, and all other values default): 
```
DB_URL="mysql://merico:XXXXXXXX@devlake.XXXXXX.us-east-2.rds.amazonaws.com:3306/devlake?charset=utf8mb4&parseTime=True"
```

My docker-compose.yml:
```
version: "3"
services:
  grafana:
    image: apache/devlake-dashboard:v0.15.0
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:4000/grafana"
      GF_USERS_DEFAULT_THEME: "light"
      MYSQL_URL: devlake.XXXXXXXX.us-east-2.rds.amazonaws.com:3306
      MYSQL_DATABASE: devlake
      MYSQL_USER: merico
      MYSQL_PASSWORD:XXXXXXXXX
    restart: always

  devlake:
    image: apache/devlake:v0.15.0
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    environment:
      LOGGING_DIR: /app/logs

  config-ui:
    image: apache/devlake-config-ui:v0.15.0
    ports:
      - 4000:4000
    env_file:
      - ./.env
    environment:
      DEVLAKE_ENDPOINT: devlake:8080
      GRAFANA_ENDPOINT: grafana:3000
      #ADMIN_USER: devlake
      #ADMIN_PASS: merico
    depends_on:
      - devlake

volumes:
  grafana-storage:
```
